(function initPlannerCatalog(globalScope) {
    const function_declarations = [
        {
            name: "execute_blockly_script",
            description: "Executes a sequence of actions on the Blockly workspace. Use this to spawn blocks, connect them, and enter text.",
            parameters: {
                type: "OBJECT",
                properties: {
                    script: {
                        type: "ARRAY",
                        description: "Ordered list of commands. Each command MUST include both 'action' and 'block'.",
                        items: {
                            type: "OBJECT",
                            properties: {
                                action: { type: "STRING", enum: ["spawn", "input"] },
                                cat: {
                                    type: "ARRAY",
                                    items: { type: "STRING" },
                                    description: "Required for action='spawn'. Category path as Msg keys.",
                                },
                                block: { type: "STRING", description: "Msg key for spawn, logical id for input." },
                                id: { type: "STRING", description: "Logical id for a spawned block." },
                                parent: { type: "STRING", description: "Logical id of a prior spawned block." },
                                pos: { type: "STRING", enum: ["nested", "next"] },
                                field: { type: "NUMBER", description: "Required for action='input'. Zero-based editable field index on the target block." },
                                field_selector: {
                                    type: "OBJECT",
                                    description: "Preferred for action='input'. Structural selector for the target field.",
                                    properties: {
                                        role: { type: "STRING", description: "Semantic field role like text, color, size, from, to, by." },
                                        index: { type: "NUMBER", description: "Fallback editable field index." },
                                        label: { type: "STRING", description: "Optional visible field label hint." },
                                        kind: { type: "STRING", enum: ["text", "dropdown", "checkbox", "unknown"] },
                                    },
                                },
                                target_block_key: { type: "STRING", description: "Optional spawned block key for executor metadata hints." },
                                value: { type: "STRING", description: "Field text or dropdown label for input." },
                            },
                            required: ["action", "block"],
                        },
                    },
                },
                required: ["script"],
            },
        },
    ];

    const tools = [{ function_declarations }];

    const NESTED_CATEGORIES = {
        CATVIRTUALACTION: "CATSMARTPHONE",
        CATADVANCEDACTION: "CATSMARTPHONE",
        CATPHYSICALSENSORS: "CATSMARTPHONE",
        CATVIRTUALSENSORS: "CATSMARTPHONE",
        CATADVANCEDSENSORS: "CATSMARTPHONE",
        CATCOMMUNICATION: "CATSMARTPHONE",
        CATDATAOPERATIONS: "CATSMARTPHONE",
        CATCOMMON: "CATWHEELS",
    };

    const BLOCK_CATEGORY_MAP = {
        INITIATE: "CATLOOPS",
        START_BLOCK: "CATLOOPS",
        STOP_TASK: "CATLOOPS",
        SETTINGS: "CATLOOPS",
        CONTROLS_REPEAT_EXT: "CATLOOPS",
        CONTROLS_WHILEUNTILFOREVER: "CATLOOPS",
        CONTROLS_FOR: "CATLOOPS",
        CONTROLS_IF: "CATLOOPS",
        CONTROLS_FLOW_STATEMENTS: "CATLOOPS",
        READ_TIMER: "CATLOOPS",
        COMPARE_TIMER: "CATLOOPS",
        WAIT_TIMER: "CATLOOPS",
        RESET_TIMER: "CATLOOPS",
        WAIT: "CATLOOPS",
        SMARTPHONE_GET_NAME: "CATLOOPS",
        SMARTPHONE_COMPARE_NAME: "CATLOOPS",
        MY_TEXT_PRINT: "CATLOOPS",
        STOP_PROGRAM: "CATLOOPS",
        LOGIC_BOOLEAN: "CATLOGIC",
        LOGIC_NEGATE: "CATLOGIC",
        LOGIC_OPERATION_EXTENDED: "CATLOGIC",
        LOGIC_NEGATE_NUMBER: "CATLOGIC",
        LOGIC_OPERATION_NUMERIC_EXTENDED: "CATLOGIC",
        LOGIC_NULL: "CATLOGIC",
        CONVERTERS_B2D: "CATLOGIC",
        CONVERTERS_D2B: "CATLOGIC",
        LOGIC_TERNARY: "CATLOGIC",
        MATH_NUMBER: "CATMATH",
        MATH_ARITHMETIC: "CATMATH",
        MATH_ADVANCED: "CATMATH",
        MATH_SINGLE: "CATMATH",
        MATH_TRIG: "CATMATH",
        MATH_CONSTANT: "CATMATH",
        MATH_ROUND: "CATMATH",
        MATH_ON_LIST: "CATMATH",
        MATH_CONSTRAIN: "CATMATH",
        MATH_RANDOM_INT: "CATMATH",
        MATH_RANDOM_FLOAT: "CATMATH",
        MATH_ATAN2: "CATMATH",
        MATH_NUMBER_PROPERTY: "CATMATH",
        LOGIC_COMPARE: "CATMATH",
        MATH_IN_RANGE: "CATMATH",
        MY_TEXT: "CATTEXT",
        TEXT_JOIN: "CATTEXT",
        MY_TEXT_APPEND: "CATTEXT",
        TEXT_LENGTH: "CATTEXT",
        LOGIC_TEXT_COMPARE: "CATTEXT",
        TEXT_ISEMPTY: "CATTEXT",
        TEXT_INDEXOF: "CATTEXT",
        NUMBER_OCCURRENCE: "CATTEXT",
        TEXT_CHARAT: "CATTEXT",
        TEXT_GETSUBSTRING: "CATTEXT",
        TEXT_CHANGECASE: "CATTEXT",
        TEXT_TRIM: "CATTEXT",
        TRANSLATE: "CATTEXT",
        RUN_LINK: "CATTEXT",
        LISTS_CREATE_WITH: "CATLISTS",
        LISTS_REPEAT: "CATLISTS",
        LISTS_LENGTH: "CATLISTS",
        LISTS_ISEMPTY: "CATLISTS",
        LISTS_INDEXOF: "CATLISTS",
        LISTS_GETINDEX: "CATLISTS",
        LISTS_SETINDEX: "CATLISTS",
        LISTS_GETSUBLIST: "CATLISTS",
        LISTS_SPLIT: "CATLISTS",
        LISTS_SORT: "CATLISTS",
        LCD_TEXT: "CATVIRTUALACTION",
        LCD_MESSAGE: "CATVIRTUALACTION",
        READ_SSEGMENT: "CATVIRTUALACTION",
        SSEGMENT: "CATVIRTUALACTION",
        BAR: "CATVIRTUALACTION",
        READ_LED: "CATVIRTUALACTION",
        LED: "CATVIRTUALACTION",
        LED_BIT: "CATVIRTUALACTION",
        LED_ADVANCED_INTERNAL: "CATVIRTUALACTION",
        LED_ADVANCED_EXTERNAL: "CATVIRTUALACTION",
        RESET_GRAPH: "CATVIRTUALACTION",
        GRAPH: "CATVIRTUALACTION",
        GRAPH_DA: "CATVIRTUALACTION",
        GET_GRAPH_TRENDLINE: "CATVIRTUALACTION",
        GRAPH_TRENDLINE: "CATVIRTUALACTION",
        GRAPH_FILE: "CATVIRTUALACTION",
        GRAPH_SAVE: "CATVIRTUALACTION",
        SHOW_COMPONENT: "CATVIRTUALACTION",
        CLEAR_COMPONENT: "CATVIRTUALACTION",
        CLEARSCREEN: "CATVIRTUALACTION",
        PLAYTONE: "CATADVANCEDACTION",
        PLAYNOTE: "CATADVANCEDACTION",
        SHOWIMAGE: "CATADVANCEDACTION",
        IMAGE_CAPTURE: "CATADVANCEDACTION",
        PLAYVIDEO: "CATADVANCEDACTION",
        VIDEO: "CATADVANCEDACTION",
        PLAYAUDIO: "CATADVANCEDACTION",
        AUDIO_CAPTURE: "CATADVANCEDACTION",
        PREVIEW: "CATADVANCEDACTION",
        STOPMEDIA: "CATADVANCEDACTION",
        SENSOR_MEASURE: "CATPHYSICALSENSORS",
        SENSOR_COMPARE: "CATPHYSICALSENSORS",
        SENSOR_WAIT: "CATPHYSICALSENSORS",
        SENSOR_RESET: "CATPHYSICALSENSORS",
        RTC: "CATPHYSICALSENSORS",
        VIRTUAL_SENSOR_MEASURE: "CATVIRTUALSENSORS",
        VIRTUAL_SENSOR_COMPARE: "CATVIRTUALSENSORS",
        VIRTUAL_SENSOR_WAIT: "CATVIRTUALSENSORS",
        KEY1_BUTTON: "CATVIRTUALSENSORS",
        ADVANCED_SENSORS_MEASURE: "CATADVANCEDSENSORS",
        ADVANCED_SENSORS_COMPARE: "CATADVANCEDSENSORS",
        ADVANCED_SENSORS_WAIT: "CATADVANCEDSENSORS",
        FACES_POSITION: "CATADVANCEDSENSORS",
        FACES_POSITION_COMPARE: "CATADVANCEDSENSORS",
        FACES_POSITION_WAIT: "CATADVANCEDSENSORS",
        FACES_NAME: "CATADVANCEDSENSORS",
        COMPARE_FACES_NAME: "CATADVANCEDSENSORS",
        WAIT_FACES_NAME: "CATADVANCEDSENSORS",
        GOOGLE: "CATCOMMUNICATION",
        CHATGPT: "CATCOMMUNICATION",
        CHATGPT_COMPARE: "CATCOMMUNICATION",
        TELEPHONY_MEASURE: "CATCOMMUNICATION",
        TELEPHONY_COMPARE: "CATCOMMUNICATION",
        TELEPHONY_WAIT: "CATCOMMUNICATION",
        TEXTTOVOICE: "CATCOMMUNICATION",
        SENDSMS: "CATCOMMUNICATION",
        WRITE_TO_FILE: "CATDATAOPERATIONS",
        READ_FILE: "CATDATAOPERATIONS",
        DELETE_FILE: "CATDATAOPERATIONS",
        INIT_DB: "CATDATAOPERATIONS",
        WRITE_DB: "CATDATAOPERATIONS",
        READ_DB: "CATDATAOPERATIONS",
        KEY_EXISTS: "CATDATAOPERATIONS",
        CHANGE_DB: "CATDATAOPERATIONS",
        DELETE_KEY: "CATDATAOPERATIONS",
        DELETE_DB: "CATDATAOPERATIONS",
        INIT_STORAGE: "CATDATAOPERATIONS",
        UPLOAD_STORAGE: "CATDATAOPERATIONS",
        DOWNLOAD_STORAGE: "CATDATAOPERATIONS",
        DELETE_STORAGE: "CATDATAOPERATIONS",
        MOVE_STEERING: "CATCOMMON",
        MOVE_DIRECTION: "CATCOMMON",
        MOVE_TANK: "CATCOMMON",
        LARGE_MOTOR: "CATCOMMON",
        UNREGULATED_MOTOR: "CATCOMMON",
        MOTOR_READY: "CATCOMMON",
        MOTOR_PORTS: "CATCOMMON",
        RESET_SENSOR: "CATCOMMON",
        READ_SENSOR: "CATCOMMON",
        COMPARE_SENSOR: "CATCOMMON",
        WAIT_SENSOR: "CATCOMMON",
        VAR_GET: "CATVARIABLES",
        VAR_SET: "CATVARIABLES",
        VAR_CHANGE: "CATVARIABLES",
        VAR_TOGGLE: "CATVARIABLES",
        VARIABLES_GET: "CATVARIABLES",
        VARIABLES_SET: "CATVARIABLES",
        MATH_CHANGE: "CATVARIABLES",
    };

    const GEMINI_MODEL = "gemini-3.1-flash-lite";

    const LED_OPTION_MAP = { red: "0", yellow: "1", green: "2", blue: "3", plug: "-1" };

    const BLOCK_METADATA = {
        INITIATE: {
            blockType: "initiate_block",
            kind: "statement",
            attachment_default: "root",
            categoryPath: ["CATLOOPS"],
            statementInput: "DO",
            field_specs: [],
        },
        START_BLOCK: {
            blockType: "start_block",
            kind: "statement",
            attachment_default: "root",
            categoryPath: ["CATLOOPS"],
            statementInput: "DO",
            field_specs: [
                { role: "task_name", kind: "dropdown", priority: 0, fieldName: "task_name" },
            ],
        },
        RESET_GRAPH: {
            blockType: "reset_graph",
            kind: "statement",
            attachment_default: "statement_nested",
            categoryPath: ["CATSMARTPHONE", "CATVIRTUALACTION"],
            field_specs: [
                { role: "color", kind: "dropdown", priority: 0, fieldName: "Color", optionMap: LED_OPTION_MAP },
            ],
        },
        CONTROLS_FOR: {
            blockType: "controls_for",
            kind: "statement",
            attachment_default: "statement_next",
            categoryPath: ["CATLOOPS"],
            statementInput: "DO",
            field_specs: [
                { role: "loop_var", kind: "dropdown", priority: 0, fieldName: "VAR" },
            ],
            valueInputs: [
                { role: "from", inputName: "FROM", literalKind: "number" },
                { role: "to", inputName: "TO", literalKind: "number" },
                { role: "by", inputName: "BY", literalKind: "number" },
            ],
            valueSockets: ["FROM", "TO", "BY"],
        },
        LCD_MESSAGE: {
            blockType: "lcd_message",
            kind: "statement",
            attachment_default: "statement_nested",
            categoryPath: ["CATSMARTPHONE", "CATVIRTUALACTION"],
            field_specs: [
                { role: "color", kind: "dropdown", priority: 0, fieldName: "Color", optionMap: LED_OPTION_MAP },
            ],
            valueInputs: [
                { role: "text", inputName: "TextInput", literalKind: "text" },
            ],
            valueSockets: ["TextInput"],
        },
        GRAPH: {
            blockType: "graph",
            kind: "statement",
            attachment_default: "statement_nested",
            categoryPath: ["CATSMARTPHONE", "CATVIRTUALACTION"],
            field_specs: [
                { role: "color", kind: "dropdown", priority: 0, fieldName: "Color", optionMap: LED_OPTION_MAP },
                { role: "clear", kind: "checkbox", priority: 1, fieldName: "Clear" },
            ],
            valueInputs: [
                { role: "x", inputName: "x", literalKind: "number" },
                { role: "y", inputName: "y", literalKind: "number" },
            ],
            valueSockets: ["x", "y"],
        },
        MATH_TRIG: {
            blockType: "math_trig",
            kind: "value",
            attachment_default: "value_nested",
            categoryPath: ["CATMATH"],
            field_specs: [
                { role: "operation", kind: "dropdown", priority: 0, fieldName: "OP" },
            ],
            valueInputs: [
                { role: "value", inputName: "NUM", literalKind: "number" },
            ],
            valueSockets: ["NUM"],
        },
        MATH_NUMBER: {
            blockType: "math_number",
            kind: "value",
            attachment_default: "value_nested",
            categoryPath: ["CATMATH"],
            field_specs: [
                { role: "value", kind: "text", priority: 0, fieldName: "NUM" },
            ],
        },
        MY_TEXT: {
            blockType: "my_text",
            kind: "value",
            attachment_default: "value_nested",
            categoryPath: ["CATTEXT"],
            field_specs: [
                { role: "text", kind: "text", priority: 0, fieldName: "TEXT" },
            ],
        },
        VAR_GET: {
            blockType: "variables_get",
            kind: "value",
            attachment_default: "value_nested",
            categoryPath: ["CATVARIABLES"],
            field_specs: [
                { role: "variable", kind: "dropdown", priority: 0, fieldName: "VAR" },
            ],
        },
        VARIABLES_GET: {
            blockType: "variables_get",
            kind: "value",
            attachment_default: "value_nested",
            categoryPath: ["CATVARIABLES"],
            field_specs: [
                { role: "variable", kind: "dropdown", priority: 0, fieldName: "VAR" },
            ],
        },
        VAR_SET: {
            blockType: "variables_set",
            kind: "statement",
            attachment_default: "statement_nested",
            categoryPath: ["CATVARIABLES"],
            field_specs: [
                { role: "variable", kind: "dropdown", priority: 0, fieldName: "VAR" },
            ],
            valueInputs: [
                { role: "value", inputName: "VALUE", literalKind: "unknown" },
            ],
            valueSockets: ["VALUE"],
        },
        VARIABLES_SET: {
            blockType: "variables_set",
            kind: "statement",
            attachment_default: "statement_nested",
            categoryPath: ["CATVARIABLES"],
            field_specs: [
                { role: "variable", kind: "dropdown", priority: 0, fieldName: "VAR" },
            ],
            valueInputs: [
                { role: "value", inputName: "VALUE", literalKind: "unknown" },
            ],
            valueSockets: ["VALUE"],
        },
    };

    globalScope.BlocklyPlannerCatalog = {
        function_declarations,
        tools,
        NESTED_CATEGORIES,
        BLOCK_CATEGORY_MAP,
        BLOCK_METADATA,
        GEMINI_MODEL,
    };
})(self);
